FROM node:22-alpine
WORKDIR /app
 
COPY frontend/build ./build
COPY frontend/package.json .

RUN npm install --omit=dev \
    && chown -R nobody:nobody /app

EXPOSE 3000

USER nobody

ENTRYPOINT ["node", "build"]