FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/* # dont forget to change when alpine

ARG SERVICE
COPY publish/${SERVICE} .

EXPOSE 8080
ENTRYPOINT dotnet ${SERVICE_DLL}