FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

RUN chown -R nobody:nobody /var/cache/nginx /var/log/nginx /etc/nginx/conf.d \
    && touch /run/nginx.pid \
    && chown nobody:nobody /run/nginx.pid

USER nobody

EXPOSE 80