FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg

ARG SERVICE

COPY publish/${SERVICE}/ .

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "dotnet $(ls *.runtimeconfig.json | head -1 | sed 's/.runtimeconfig.json/.dll/')"]