events {
    worker_connections 1024;
}


http {




    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;




    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    large_client_header_buffers 4 16k;




    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;




    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;


    server {


        listen 8080;
        server_name _;




        location /api/auth/ {
            proxy_pass http://auth-service:8080/;
        }


        location /api/voki-storage/ {
            proxy_pass http://vokimi-storage-service:8080/;
        }


        location /api/voki-creation/core/ {
            proxy_pass http://core-voki-creation-service:8080/;
        }


        location /api/voki-creation/general/ {
            proxy_pass http://general-voki-creation-service:8080/;
        }


        location /api/voki-taking/general/ {
            proxy_pass http://general-voki-taking-service:8080/;
        }


        location /api/tags/ {
            proxy_pass http://tags-service:8080/;
        }


        location /api/user-profiles/ {
            proxy_pass http://user-profiles-service:8080/;
        }


        location /api/vokis-catalog/ {
            proxy_pass http://vokis-catalog-service:8080/;
        }


        location /api/albums/ {
            proxy_pass http://albums-service:8080/;
        }


        location /api/voki-comments/ {
            proxy_pass http://voki-comments-service:8080/;
        }


        location /api/voki-ratings/ {
            proxy_pass http://voki-ratings-service:8080/;
        }


       
        location / {
            proxy_pass http://frontend:3000;
        }


    }
}
