global using System.Diagnostics.Contracts;
global using SharedKernel;
global using SharedKernel.common;
global using SharedKernel.domain;
global using SharedKernel.domain.ids;
global using SharedKernel.errs;
global using SharedKernel.errs.utils;
global using SharedKernel.exceptions;
global using SharedKernel.user_ctx;