global using System.Collections.Immutable;
global using ApplicationShared;
global using ApplicationShared.messaging;
global using ApplicationShared.messaging.pipeline_behaviors;
global using SharedKernel.common;
global using SharedKernel.domain.ids;
global using SharedKernel.errs;
global using SharedKernel.errs.utils;
global using SharedKernel.exceptions;
