global using System.Collections.Immutable;
global using System.Diagnostics.Contracts;
global using SharedKernel.common;
global using SharedKernel.common.vokis;
global using SharedKernel.domain;
global using SharedKernel.domain.ids;
global using SharedKernel.errs;
global using SharedKernel.errs.utils;
global using SharedKernel.user_ctx;